// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Mutation struct {
}

type Query struct {
}

type Room struct {
	Name        string  `json:"name"`
	Folder      *string `json:"folder,omitempty"`
	Description *string `json:"description,omitempty"`
	Position    int     `json:"position"`
}

type Subscription struct {
}

type User struct {
	Name   string  `json:"name"`
	Avatar *string `json:"avatar,omitempty"`
}
