package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"uchat/chat"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, name string, folder *string, description *string) (*Room, error) {
	if err := chat.ValidateRoomName(name); err != nil {
		return nil, err
	}
	f := ""
	if folder != nil {
		f = *folder
		if f != "" {
			if err := chat.ValidateRoomName(f); err != nil {
				return nil, err
			}
		}
	}
	row, err := r.Store.CreateRoom(ctx, name, f, description)
	if err != nil {
		return nil, err
	}
	return &Room{Name: row.Name, Folder: ptrIfNonEmpty(row.Folder), Description: row.Description, Position: row.Position}, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, room string, user string, body chat.Body, source *string, streaming *chat.Timestamp) (*chat.Message, error) {
	if err := chat.ValidateRoomPath(room); err != nil {
		return nil, err
	}
	src := "web"
	if source != nil {
		src = *source
	}
	msg := chat.NewMessage(user, body, src)
	msg.Room = room
	msg.Streaming = streaming
	if err := r.Store.Send(ctx, room, msg); err != nil {
		return nil, err
	}
	folder, _ := chat.ParseRoomPath(room)
	r.Broker.Publish(room, folder, msg)
	return &msg, nil
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, id string, body chat.Body, streaming *chat.Timestamp) (*chat.Message, error) {
	if err := r.Store.EditMessage(ctx, id, body, streaming); err != nil {
		return nil, err
	}
	msg, err := r.Store.GetMessage(ctx, id)
	if err != nil {
		return nil, err
	}
	folder, _ := chat.ParseRoomPath(msg.Room)
	r.Broker.Publish(msg.Room, folder, *msg)
	return msg, nil
}

// MarkRead is the resolver for the markRead field.
func (r *mutationResolver) MarkRead(ctx context.Context, room string, user string, messageID string) (bool, error) {
	if err := chat.ValidateRoomPath(room); err != nil {
		return false, err
	}
	if err := r.Store.MarkRead(ctx, room, user, messageID); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, name string, folder *string, description *string) (*Room, error) {
	if err := chat.ValidateRoomName(name); err != nil {
		return nil, err
	}
	f := ""
	if folder != nil {
		f = *folder
		if f != "" {
			if err := chat.ValidateRoomName(f); err != nil {
				return nil, err
			}
		}
	}
	row, err := r.Store.UpdateRoom(ctx, name, f, description)
	if err != nil {
		return nil, err
	}
	return &Room{Name: row.Name, Folder: ptrIfNonEmpty(row.Folder), Description: row.Description, Position: row.Position}, nil
}

// DeleteRoom is the resolver for the deleteRoom field.
func (r *mutationResolver) DeleteRoom(ctx context.Context, name string, folder *string) (bool, error) {
	if err := chat.ValidateRoomName(name); err != nil {
		return false, err
	}
	f := ""
	if folder != nil {
		f = *folder
		if f != "" {
			if err := chat.ValidateRoomName(f); err != nil {
				return false, err
			}
		}
	}
	if err := r.Store.DeleteRoom(ctx, name, f); err != nil {
		return false, err
	}
	return true, nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, folder *string) ([]*Room, error) {
	rows, err := r.Store.ListRooms(ctx, folder)
	if err != nil {
		return nil, err
	}
	rooms := make([]*Room, len(rows))
	for i, row := range rows {
		rooms[i] = &Room{Name: row.Name, Folder: ptrIfNonEmpty(row.Folder), Description: row.Description, Position: row.Position}
	}
	return rooms, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, room string) ([]*chat.Message, error) {
	if err := chat.ValidateRoomPath(room); err != nil {
		return nil, err
	}
	msgs, err := r.Store.GetMessages(ctx, room)
	if err != nil {
		return nil, err
	}
	ptrs := make([]*chat.Message, len(msgs))
	for i := range msgs {
		ptrs[i] = &msgs[i]
	}
	return ptrs, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	var users []*User
	for name, uc := range r.Config.Users {
		u := &User{Name: name}
		if uc.Avatar != "" {
			path := "/data/" + uc.Avatar
			u.Avatar = &path
		}
		users = append(users, u)
	}
	return users, nil
}

// UnreadCounts is the resolver for the unreadCounts field.
func (r *queryResolver) UnreadCounts(ctx context.Context, user string) ([]*chat.UnreadCount, error) {
	counts, err := r.Store.GetUnreadCounts(ctx, user)
	if err != nil {
		return nil, err
	}
	ptrs := make([]*chat.UnreadCount, len(counts))
	for i := range counts {
		ptrs[i] = &counts[i]
	}
	return ptrs, nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, room *string, folder *string) (<-chan *chat.Message, error) {
	if room != nil {
		if err := chat.ValidateRoomPath(*room); err != nil {
			return nil, err
		}
	}

	// Folder subscription takes priority if provided.
	if folder != nil && *folder != "" {
		sub := r.Broker.SubscribeFolder(*folder)
		ch := make(chan *chat.Message, 64)
		go func() {
			defer r.Broker.UnsubscribeFolder(*folder, sub)
			defer close(ch)
			for {
				select {
				case msg, ok := <-sub.Messages():
					if !ok {
						return
					}
					ch <- &msg
				case <-ctx.Done():
					return
				}
			}
		}()
		return ch, nil
	}

	roomStr := ""
	if room != nil {
		roomStr = *room
	}
	sub := r.Broker.Subscribe(roomStr)
	ch := make(chan *chat.Message, 64)
	go func() {
		defer r.Broker.Unsubscribe(roomStr, sub)
		defer close(ch)
		for {
			select {
			case msg, ok := <-sub.Messages():
				if !ok {
					return
				}
				ch <- &msg
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

